// Constantes de l'application

const STATUTS = {
  TONTINE: {
    EN_ATTENTE: 'EN_ATTENTE',
    ACTIVE: 'ACTIVE',
    TERMINEE: 'TERMINEE',
    ANNULEE: 'ANNULEE'
  },
  COTISATION: {
    EN_ATTENTE: 'EN_ATTENTE',
    PAYEE: 'PAYEE',
    EN_RETARD: 'EN_RETARD',
    ANNULEE: 'ANNULEE'
  },
  DISTRIBUTION: {
    PLANIFIEE: 'PLANIFIEE',
    EFFECTUEE: 'EFFECTUEE',
    ANNULEE: 'ANNULEE'
  },
  INVITATION: {
    EN_ATTENTE: 'EN_ATTENTE',
    ACCEPTEE: 'ACCEPTEE',
    REFUSEE: 'REFUSEE',
    EXPIREE: 'EXPIREE'
  },
  USER: {
    ACTIF: 'ACTIF',
    INACTIF: 'INACTIF',
    SUSPENDU: 'SUSPENDU',
    BANNI: 'BANNI'
  },
  VERIFICATION: {
    NON_SOUMIS: 'NON_SOUMIS',
    EN_ATTENTE: 'EN_ATTENTE',
    VERIFIE: 'VERIFIE',
    REJETE: 'REJETE'
  }
};

const FREQUENCES = {
  QUOTIDIENNE: 'QUOTIDIENNE',
  HEBDOMADAIRE: 'HEBDOMADAIRE',
  MENSUELLE: 'MENSUELLE',
  TRIMESTRIELLE: 'TRIMESTRIELLE'
};

const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

const TYPES_NOTIFICATION = {
  TONTINE_DEMARREE: 'TONTINE_DEMARREE',
  COTISATION_RAPPEL: 'COTISATION_RAPPEL',
  COTISATION_RETARD: 'COTISATION_RETARD',
  DISTRIBUTION_PRETE: 'DISTRIBUTION_PRETE',
  DISTRIBUTION_EFFECTUEE: 'DISTRIBUTION_EFFECTUEE',
  INVITATION_RECUE: 'INVITATION_RECUE',
  MEMBRE_REJOINT: 'MEMBRE_REJOINT',
};

module.exports = {
  STATUTS,
  FREQUENCES,
  ROLES,
  TYPES_NOTIFICATION
};
